-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "fromDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "toDate" TIMESTAMP(3),
ADD COLUMN     "willRepeatEveryWeek" BOOLEAN NOT NULL DEFAULT false;
